var email = document.querySelectorAll("#email2");
var btnSignUp = document.querySelector("#sign-up");
var btnEnter = document.querySelector("#open-enter");
var enterForm = document.querySelector("#enter-form");
var pas = document.querySelectorAll("#password2, #password3");
var enterCloseBtn = document.querySelector("#enter-form .close");
var btnregistration = document.querySelector("#open-registration");
var registrationForm = document.querySelector("#registration-form");
var registrationCloseBtn = document.querySelector("#registration-form .close2");
